server:
    port: 9296

spring:
    application:
        name: CONFIG-SERVICE
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/shamesh/config-server
                    clone-on-start: true


  
