server:
  port: 9191

#Removed from here as these will be pulled in from the cloud config server as defined in bootstrap.yml config file
#eureka:
 # client:
  #  register-with-eureka: true
   # fetch-registry: true
    #service-url:
     # defaultZone: http://localhost:8761/eureka/
  #instance:
   # hostname: localhost

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**